---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets-ns


---
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-rabbitmq-registry-creds
  namespace: secrets-ns
type: kubernetes.io/dockerconfigjson   # needs to be this type
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.tanzu.vmware.com": {
          "username": "USERNAME",
          "password": "PASSWORD",
          "auth": ""
        }
      }
    }

---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tanzu-rabbitmq-registry-creds    # must match source secret name
  namespace: secrets-ns                  # must match source secret namespace
spec:
  toNamespaces:
  - "*"  # star means export is available for all namespaces
---
