---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-overlay
  namespace: tanzu-package-repo-global
stringData:
  add-placeholder-secret.yml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: tanzu-rabbitmq-registry-creds
      annotations:
        secretgen.carvel.dev/image-pull-secret: ""
    type: kubernetes.io/dockerconfigjson
    data:
      .dockerconfigjson: e30K
  add-placeholder-namespace.yml: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Secret","metadata": {"name":"tanzu-rabbitmq-registry-creds"}}),expects="1+"
    ---
    metadata:
      #@overlay/match missing_ok=True
      namespace: #@ data.values.namespace
  add-image-pull-secret.yml: |
    #@ load("@ytt:overlay", "overlay")
    #@overlay/match by=overlay.subset({"kind":"Deployment"}),expects="1+"
    ---
    spec:
      template:
        spec:
          #@overlay/match missing_ok=True
          imagePullSecrets:
            - name: tanzu-rabbitmq-registry-creds
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager-rabbitmq
  namespace: tanzu-package-repo-global
  annotations:
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: cert-manager-overlay
spec:
  serviceAccountName: tanzu-rabbitmq
  packageRef:
    refName: cert-manager.rabbitmq.tanzu.vmware.com
    versionSelection:
      constraints: 1.5.3+rmq

